// <auto-generated />
namespace Project_Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Doctor_Customer_Many2Many_Resolved_By_Appointment2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Doctor_Customer_Many2Many_Resolved_By_Appointment2));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281041310_Doctor_Customer_Many2Many_Resolved_By_Appointment2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
